context:
  name: libscrypt
  version: "1.22"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/technion/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a2d30ea16e6d288772791de68be56153965fe4fd4bcd787777618b8048708936

build:
  skip:
    - win
  script:
    - make install${{ '-osx' if osx else '' }} PREFIX=$PREFIX
    - make install-static PREFIX=$PREFIX
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  run_exports:
    - ${{ pin_subpackage(name) }}

tests:
  - package_contents:
      include:
        - libscrypt.h
      lib:
        - scrypt
about:
  homepage: https://github.com/technion/libscrypt
  summary: Library for scrypt
  license: BSD-2-Clause
  license_file: LICENSE
  repository: https://github.com/technion/libscrypt

extra:
  recipe-maintainers:
    - pavelzw
